workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 120
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.vrisham.customerapp"
        APP_STORE_CONNECT_ISSUER_ID: 7ed17a9f-e39c-4b71-8aec-8ae25bc633dd
        APP_STORE_CONNECT_KEY_IDENTIFIER: 3QB8N96NNN
        APP_STORE_CONNECT_PRIVATE_KEY: |
          -----BEGIN PRIVATE KEY-----
          MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgcBcVs1KUmutJIwO9
          Y6b52ugL2cCMEC9YZvnojDW8p0WgCgYIKoZIzj0DAQehRANCAARcG8eVAT8ibspF
          iIu5Uv7ebeey4m/+q85qLWj8M1lkiGgVDXGdg0ZATwSDpQxAf3NaxwSodG/mLZsN
          Cn2q9byX
          -----END PRIVATE KEY-----
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install -g @ionic/cli
      - name: Build web app and sync with Capacitor
        script: |
          ionic build
          ionic cap sync ios
          cd ios/App
          pod install --repo-update
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Increment build number
        script: |
          cd ios/App
          BUILD_NUMBER=$(($(xcodebuild -showBuildSettings -workspace App.xcworkspace -scheme $XCODE_SCHEME | grep CURRENT_PROJECT_VERSION | tr -d 'CURRENT_PROJECT_VERSION =') + 1))
          agvtool new-version -all $BUILD_NUMBER
      - name: Build iOS
        script: |
          cd ios/App
          xcodebuild clean -workspace App.xcworkspace -scheme $XCODE_SCHEME -configuration Release
          xcodebuild archive -workspace App.xcworkspace -scheme $XCODE_SCHEME -configuration Release -destination generic/platform=iOS -archivePath $CM_BUILD_DIR/App.xcarchive
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/App.xcarchive -exportPath $CM_BUILD_DIR/build/ios -exportOptionsPlist exportOptions.plist

    artifacts:
      - build/ios/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - App Store Connect Users
        submit_to_app_store: false
